/**
 * Points of interest and supply drops — GDD §06 (exploration) and §10 (Earth),
 * the content half of TDD §25 T6.
 *
 * Two different things live here, because they arrive differently:
 *
 *  - **Sites** were always on the planet. A wrecked rover, an abandoned survey
 *    camp, a meteorite, an ice cave. `World` scatters them from the seed, so
 *    two colonies on the same seed explore the same planet, and they are there
 *    whether or not anyone ever finds them. The map begins mostly unknown
 *    (GDD §06) — a site is not *on the map* until a rover or the colonist gets
 *    close enough to see it.
 *  - **Supply drops** are scheduled by the simulation, not generated by the
 *    world (GDD §10: "cargo missions arrive at uncertain locations, marked by
 *    transponders"). They land after the mission starts, the transponder
 *    announces them, and dust buries them if nobody comes — a storm buries them
 *    faster, which is the decision the design asks the player to make.
 *
 * Both are one shape, `Poi`, so the renderer, the HUD and the salvage task have
 * exactly one thing to handle. A drop is a `Poi` with `kind: 'supplyDrop'` and a
 * burial countdown; a site has no countdown and never disappears.
 *
 * What a manifest may contain is limited by the economy that exists: bulk
 * resources that ride in a rover's hold and battery cells that land in the
 * grid store. Fluids are deliberately excluded: exposed water and food cargo
 * would freeze, and the current logistics model has no field-fluid recovery.
 *
 * Everything here is pure and seeded. No `Math.random`, no clock, no DOM: the
 * generation is replayable, which is what lets a save regenerate a site it never
 * wrote down and keeps the determinism suites honest.
 */

import type { ResourceId } from './defs';
import {
  DROP_BURY_SOLS,
  DROP_RING_INNER_FRAC,
  DROP_RING_OUTER_FRAC,
  DROP_STORM_BURY_RATE,
  POI_SALVAGE_RATE_KG_S,
  SPAWN_RADIUS,
} from './config';

// ------------------------------------------------------------------ kinds ----

export type PoiKind =
  /** Earth cargo container, transponder-marked (GDD §10). */
  | 'supplyDrop'
  /** An old rover, salvageable rather than repairable (GDD §06). */
  | 'wreckRover'
  /** An abandoned camp: hardware, panels, structural scrap. */
  | 'abandonedMission'
  /** A meteorite — geological sample, and a lot of iron. */
  | 'meteorite'
  /** An ice cave or lava tube mouth: a major water source in the open. */
  | 'iceCave'
  /** Scientific equipment and a data cache, mostly electronics. */
  | 'scienceCache'
  /** A flat, sheltered spot worth building on. Marker only — nothing to haul. */
  | 'settlementSite';

export const ALL_POI_KINDS: PoiKind[] = [
  'supplyDrop',
  'wreckRover',
  'abandonedMission',
  'meteorite',
  'iceCave',
  'scienceCache',
  'settlementSite',
];

export interface PoiInfo {
  id: PoiKind;
  label: string;
  icon: string;
  blurb: string;
  /**
   * Bulk salvage this kind yields, in kg, before the generator's per-site
   * jitter. A resource absent from the table is not there to take.
   */
  salvage: Partial<Record<ResourceId, number>>;
  /** Surviving cells, in kWh, handed to the grid store. */
  energyKWh?: number;
  /** How hard the salvage is to cut free, relative to digging ore (1 = same). */
  workMul?: number;
}

/**
 * The content table. Balance lives here rather than in the salvage task, so
 * adding a new kind of site is a data edit and not a code change — the same rule
 * `defs.ts` sets for buildings and resources.
 */
export const POI_KINDS: Record<PoiKind, PoiInfo> = {
  supplyDrop: {
    id: 'supplyDrop',
    label: 'Supply Drop',
    icon: '📦',
    blurb:
      'An Earth cargo container under a transponder. Recover it before the dust does.',
    salvage: {},
  },
  wreckRover: {
    id: 'wreckRover',
    label: 'Wrecked Rover',
    icon: '🛻',
    blurb:
      'A rover from an earlier mission, rolled and dead. The frame is good aluminium and the cells may still hold.',
    salvage: { aluminum: 900, iron: 600, silicon: 180 },
    energyKWh: 45,
    workMul: 1.15,
  },
  abandonedMission: {
    id: 'abandonedMission',
    label: 'Abandoned Camp',
    icon: '⛺',
    blurb:
      'Habitat modules and truss someone left behind. Panels, wiring and a lot of structural metal.',
    salvage: { aluminum: 700, iron: 900, silicon: 420, regolith: 500 },
    energyKWh: 20,
    workMul: 1,
  },
  meteorite: {
    id: 'meteorite',
    label: 'Meteorite',
    icon: '☄',
    blurb: 'A nickel-iron fall. Nearly pure ore, and a sample worth keeping.',
    salvage: { iron: 1600, silicon: 120 },
    workMul: 1.3,
  },
  iceCave: {
    id: 'iceCave',
    label: 'Ice Cave',
    icon: '🧊',
    blurb:
      'Subsurface ice exposed at a cave mouth — water with almost no overburden to move.',
    salvage: { ice: 2200 },
    workMul: 0.8,
  },
  scienceCache: {
    id: 'scienceCache',
    label: 'Science Cache',
    icon: '🛰',
    blurb:
      'A sensor package and a data cache, still powered. Mostly electronics and glass.',
    salvage: { silicon: 700, aluminum: 260 },
    energyKWh: 60,
    workMul: 0.9,
  },
  settlementSite: {
    id: 'settlementSite',
    label: 'Settlement Site',
    icon: '🚩',
    blurb:
      'Flat, sheltered ground with a good approach. Nothing to haul — a place to build later.',
    salvage: {},
  },
};

/** Weighted pick for the generator. Settlement sites are common; caches are not. */
const KIND_WEIGHT: Record<PoiKind, number> = {
  supplyDrop: 0, // scheduled by the sim, never scattered by the world
  wreckRover: 1.6,
  abandonedMission: 1.3,
  meteorite: 2,
  iceCave: 1.5,
  scienceCache: 1,
  settlementSite: 2.2,
};

// --------------------------------------------------------------- manifests ----

/**
 * Earth cargo types (GDD §10) expressed in the resources this colony actually
 * has. A manifest is a *shape*: the generator jitters every amount, so two
 * drops of the same type are not the same drop.
 */
export interface ManifestInfo {
  id: string;
  label: string;
  salvage: Partial<Record<ResourceId, number>>;
  energyKWh?: number;
}

export const DROP_MANIFESTS: Record<string, ManifestInfo> = {
  cells: {
    id: 'cells',
    label: 'Battery cells and bus bar',
    salvage: { aluminum: 260 },
    energyKWh: 180,
  },
  parts: {
    id: 'parts',
    label: 'Replacement parts',
    salvage: { iron: 700, silicon: 320, aluminum: 380 },
  },
  machinery: {
    id: 'machinery',
    label: 'Specialised machinery',
    salvage: { iron: 900, aluminum: 520, regolith: 300 },
  },
  science: {
    id: 'science',
    label: 'Scientific equipment',
    salvage: { silicon: 620, aluminum: 180 },
    energyKWh: 90,
  },
};

export const ALL_MANIFESTS: ManifestInfo[] = Object.values(DROP_MANIFESTS);

// ----------------------------------------------------------------- the site ----

export interface Poi {
  id: number;
  kind: PoiKind;
  x: number;
  z: number;
  /** Bulk salvage still lying here, per resource. */
  salvage: Partial<Record<ResourceId, number>>;
  /** Cells still holding charge (kWh). */
  energyKWh: number;
  /**
   * False until a rover or the colonist gets within `POI_DISCOVER_M`.
   * Undiscovered sites are simulated (they are on the planet) but not drawn,
   * not marked and not orderable — GDD §06's "map begins mostly unknown".
   */
  discovered: boolean;
  /** Supply drops only: sols of dust cover left before the cargo is lost. */
  solsToBury: number;
  /** True once the dust won. The container stays on the map as a dead marker. */
  buried: boolean;
  /** The cargo label Earth sent, for the transponder line and the inspector. */
  manifest: string;
}

/** Total bulk salvage left at a site, in kg. */
export function salvageTotalKg(p: Poi): number {
  let total = 0;
  for (const v of Object.values(p.salvage)) total += v;
  return total;
}

/**
 * True when there is nothing left at the site worth sending a rover for.
 *
 * This asks about **bulk salvage only** — what a rover can cut free and carry.
 * Surviving cells are deliberately not part of it: they are handed over by
 * `recoverSiteCells` at the moment the bulk runs out, and gating on them too
 * would mean a container with 60 kWh of cells could never
 * be declared empty, because the cells are only taken once it is.
 */
export function isPickedClean(p: Poi): boolean {
  if (p.kind === 'settlementSite') return true; // a marker, never a job
  return salvageTotalKg(p) <= 0.5;
}

/**
 * How fast a rover cuts salvage free here, in kg per game second. The same
 * weather and drivetrain multipliers that govern mining apply on top of this.
 */
export function salvageRateKgS(kind: PoiKind): number {
  return POI_SALVAGE_RATE_KG_S / (POI_KINDS[kind].workMul ?? 1);
}

/** kg of salvage a rover takes per game second, spread across its contents. */
export function takeSalvage(
  p: Poi,
  roomKg: number,
  rateKgS: number,
  dtS: number,
): { takenKg: number; perResource: Partial<Record<ResourceId, number>> } {
  const want = Math.max(0, Math.min(roomKg, rateKgS * dtS));
  const available = salvageTotalKg(p);
  if (want <= 0 || available <= 0) return { takenKg: 0, perResource: {} };
  const frac = Math.min(1, want / available);
  const perResource: Partial<Record<ResourceId, number>> = {};
  let takenKg = 0;
  for (const [res, amount] of Object.entries(p.salvage)) {
    if (!amount || amount <= 0) continue;
    const take = amount * frac;
    p.salvage[res as ResourceId] = amount - take;
    perResource[res as ResourceId] = take;
    takenKg += take;
  }
  return { takenKg, perResource };
}

/**
 * Build one site. `rng` decides the per-site jitter and which resource mix a
 * generic kind carries, so a seed reproduces its planet exactly.
 */
export function makePoi(
  id: number,
  kind: PoiKind,
  x: number,
  z: number,
  rng: () => number,
): Poi {
  const info = POI_KINDS[kind];
  const jitter = 0.7 + rng() * 0.6; // 0.7× – 1.3×
  const salvage: Partial<Record<ResourceId, number>> = {};
  for (const [res, kg] of Object.entries(info.salvage)) {
    salvage[res as ResourceId] = (kg ?? 0) * jitter;
  }
  return {
    id,
    kind,
    x,
    z,
    salvage,
    energyKWh: (info.energyKWh ?? 0) * jitter,
    discovered: false,
    solsToBury: 0,
    buried: false,
    manifest: '',
  };
}

/**
 * Build one supply drop. Manifest choice and amounts come from `rng`; the
 * burial clock starts at `DROP_BURY_SOLS` and the storm multiplier is applied by
 * the simulation, which is the only thing that knows the sky.
 */
export function makeSupplyDrop(
  id: number,
  x: number,
  z: number,
  rng: () => number,
): Poi {
  const info = ALL_MANIFESTS[Math.min(ALL_MANIFESTS.length - 1, Math.floor(rng() * ALL_MANIFESTS.length))];
  const jitter = 0.75 + rng() * 0.5;
  const salvage: Partial<Record<ResourceId, number>> = {};
  for (const [res, kg] of Object.entries(info.salvage)) {
    salvage[res as ResourceId] = (kg ?? 0) * jitter;
  }
  return {
    id,
    kind: 'supplyDrop',
    x,
    z,
    salvage,
    energyKWh: (info.energyKWh ?? 0) * jitter,
    discovered: true, // the transponder gives the bearing; you still have to look
    solsToBury: DROP_BURY_SOLS,
    buried: false,
    manifest: info.label,
  };
}

// ------------------------------------------------------------ generation ----

/**
 * Weighted kind pick, excluding anything with zero weight (supply drops are
 * scheduled, never scattered). Kept exported because a test pins that every
 * kind the table names is reachable — a zero-weight typo otherwise deletes a
 * feature quietly.
 */
export function pickPoiKind(rng: () => number): PoiKind {
  let total = 0;
  for (const k of ALL_POI_KINDS) total += KIND_WEIGHT[k];
  let roll = rng() * total;
  for (const k of ALL_POI_KINDS) {
    roll -= KIND_WEIGHT[k];
    if (roll <= 0) return k;
  }
  return 'meteorite';
}

/** Kinds the world generator is allowed to scatter. */
export function scatterableKinds(): PoiKind[] {
  return ALL_POI_KINDS.filter((k) => KIND_WEIGHT[k] > 0);
}

/**
 * Where a drop lands: far enough out that recovery is an expedition, close
 * enough in that it is not a fool's errand on a flat battery. GDD §10 wants the
 * location uncertain; the ring makes it a decision rather than a lottery.
 */
export function rollDropRing(rng: () => number, worldHalf: number): { min: number; max: number } {
  const inner = Math.min(worldHalf - 60, Math.max(SPAWN_RADIUS + 120, worldHalf * DROP_RING_INNER_FRAC));
  const outer = Math.max(inner + 60, worldHalf * DROP_RING_OUTER_FRAC);
  return { min: inner, max: outer };
}

/** How fast a drop's burial clock runs under a given storm intensity. */
export function burialRate(stormIntensity: number): number {
  if (stormIntensity <= 0.05) return 1;
  return 1 + (DROP_STORM_BURY_RATE - 1) * Math.min(1, stormIntensity);
}
